# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(verbose_name='Estado da comunicação')),
            ],
            options={
                'verbose_name': 'Configurações da comunicação MQTT',
            },
        ),
    ]
