# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0002_mqtt'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='descricao',
            field=models.CharField(default="Central", max_length=255, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mqtt',
            name='servidor',
            field=models.CharField(default='nectar.videira.ifc.edu.br', max_length=255, verbose_name='Endereço do servidor'),
            preserve_default=False,
        ),
    ]
