# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0005_auto_20170618_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt',
            name='status',
            field=models.IntegerField(choices=[(0, 'Não configurado'), (1, 'Funcionando'), (2, 'Falha na comunicação'), (3, 'Erro')], default=0, verbose_name='Estado da comunicação'),
        ),
    ]
