# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0006_auto_20170618_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt',
            name='descricao',
            field=models.CharField(max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='mqtt',
            name='servidor',
            field=models.CharField(max_length=255, null=True, verbose_name='Endereço do servidor'),
        ),
    ]
